with-expecter: True
#inpackage-suffix: true
disable-version-string: true
filename: "mock_{{.InterfaceName | lower }}.go"
mockname: "{{ .Mock }}{{ .InterfaceName }}"
dir: "{{ .InterfaceDirRelative}}"
packages:
  github.com/mxpaul/httpoh:
    interfaces:
      # select the interfaces you want mocked
      Request:
      Response:
