// Code generated by mockery. DO NOT EDIT.

package httpoh

import (
	context "context"

	httpoh "github.com/mxpaul/httpoh"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// PerformRequest provides a mock function with given fields: ctx, req, res
func (_m *MockClient) PerformRequest(ctx context.Context, req httpoh.Request, res httpoh.Response) error {
	ret := _m.Called(ctx, req, res)

	if len(ret) == 0 {
		panic("no return value specified for PerformRequest")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, httpoh.Request, httpoh.Response) error); ok {
		r0 = rf(ctx, req, res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_PerformRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PerformRequest'
type MockClient_PerformRequest_Call struct {
	*mock.Call
}

// PerformRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - req httpoh.Request
//   - res httpoh.Response
func (_e *MockClient_Expecter) PerformRequest(ctx interface{}, req interface{}, res interface{}) *MockClient_PerformRequest_Call {
	return &MockClient_PerformRequest_Call{Call: _e.mock.On("PerformRequest", ctx, req, res)}
}

func (_c *MockClient_PerformRequest_Call) Run(run func(ctx context.Context, req httpoh.Request, res httpoh.Response)) *MockClient_PerformRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(httpoh.Request), args[2].(httpoh.Response))
	})
	return _c
}

func (_c *MockClient_PerformRequest_Call) Return(_a0 error) *MockClient_PerformRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_PerformRequest_Call) RunAndReturn(run func(context.Context, httpoh.Request, httpoh.Response) error) *MockClient_PerformRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
